-- ==============================================================================
-- V1__init_schema.sql - Smart Wardrobe Baseline Schema
-- Supports both PostgreSQL 14+ and H2 (ANSI Standard SQL)
-- ==============================================================================

-- 1. Users Table (Authentication & Multi-Tenancy)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Clothing Items Table
CREATE TABLE IF NOT EXISTS clothing_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    sub_category VARCHAR(100),
    primary_color VARCHAR(100) NOT NULL,
    secondary_color VARCHAR(100),
    pattern VARCHAR(100),
    style VARCHAR(50) NOT NULL DEFAULT 'CASUAL',
    season VARCHAR(50) NOT NULL DEFAULT 'ALL_SEASON',
    warmth_level INT DEFAULT 2,
    image_url TEXT,
    favorite BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE clothing_items ADD COLUMN IF NOT EXISTS user_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_clothing_user_cat ON clothing_items(user_id, category);
CREATE INDEX IF NOT EXISTS idx_clothing_user_fav ON clothing_items(user_id, favorite);

-- 3. Outfits Table
CREATE TABLE IF NOT EXISTS outfits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    name VARCHAR(255) NOT NULL,
    occasion VARCHAR(255) NOT NULL,
    weather_condition VARCHAR(255),
    styling_advice TEXT,
    color_palette VARCHAR(255),
    favorite BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE outfits ADD COLUMN IF NOT EXISTS user_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_outfits_user ON outfits(user_id);

-- 4. Outfit Items Join Table (Many-to-Many)
CREATE TABLE IF NOT EXISTS outfit_items (
    outfit_id BIGINT NOT NULL,
    clothing_item_id BIGINT NOT NULL,
    PRIMARY KEY (outfit_id, clothing_item_id)
);
